name: Android CI

on:
  pull_request:
    branches: [ "competition-code" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
  
      - name: Set current date as environment variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
  
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
  
      # Create the Release APK
      - name: Build TeamCode release APK
        run: ./gradlew :TeamCode:assembleRelease --stacktrace --no-daemon --parallel
  
      - uses: r0adkll/sign-android-release@v1
        name: Sign TeamCode release APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: TeamCode/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEYSTORE_BASE64 }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
    
      - name: Upload TeamCode release APK
        uses: actions/upload-artifact@v4
        with:
          name: TeamCode-release-${{ env.date_today }}
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
  
      # Create the Debug APK
      - name: Build TeamCode debug APK
        run: ./gradlew :TeamCode:assembleDebug --stacktrace --no-daemon --parallel
  
      - name: Upload TeamCode debug APK
        uses: actions/upload-artifact@v4
        with:
          name: TeamCode-debug-${{ env.date_today }}
          path: TeamCode/build/outputs/apk/debug/TeamCode-debug.apk
